# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, test-action ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build
        run: |
          apt-get install --yes postgresql
          psql -c 'CREATE DATABASE pomm_test' -U postgres -h 127.0.0.1 postgres
          psql -c 'CREATE EXTENSION hstore' -U postgres -h 127.0.0.1 pomm_test
          psql -c 'CREATE EXTENSION ltree' -U postgres -h 127.0.0.1 pomm_test
          composer install
          cp sources/tests/config.travis.php sources/tests/config.php

      # Runs a set of commands using the runners shell
      - name: run test
        run: bin/vendor/atoum -d sources/tests/Unit
